SourceCode/NGOWebsite/NGOWebsite/Areas/Admin/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BusinessLogicLayer;

namespace NGOWebsite.Areas.Admin.Controllers
{
    public class MenusController : Controller
    {
        //
        // GET: /Admin/Menu/

        public ActionResult ListMenu()
        {
            if (Session["mvc_user"] != null)
            {
                Models.Admin ad = Session["mvc_user"] as Models.Admin;
                if (!ad.IsSuperAdmin)
                {
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }

            List<Menu> ls = MenuBusiness.GetAllMenu();

            return View(ls);
        }

        //
        // GET: /Admin/Menu/Details/5

        public ActionResult Details(int id)
        {
            if (Session["mvc_user"] != null)
            {
                Models.Admin ad = Session["mvc_user"] as Models.Admin;
                if (!ad.IsSuperAdmin)
                {
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }

            List<Menu> ls = MenuBusiness.GetMenuById(id);

            return View(ls[0]);
        }

        //
        // GET: /Admin/Menu/Create

        public ActionResult Create()
        {
            if (Session["mvc_user"] != null)
            {
                Models.Admin ad = Session["mvc_user"] as Models.Admin;
                if (!ad.IsSuperAdmin)
                {
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }
            return View();
        }


        [HttpPost]
        public JsonResult CheckSubjectExisted(string subject, int? id)
        {
            bool check = false;
            List<Models.Menu> ls = MenuBusiness.CheckMenuExisted(subject, id);
            if (ls.Count > 0)
            {
                check = true;
            }
            return Json(check == false);
        }
        //
        // POST: /Admin/Menu/Create

        [HttpPost]
        public ActionResult CreateProcess(FormCollection frm)
        {
            int kt = 0;
            try
            {

                int? postion = null;
                if (frm["Position"] != null && frm["Position"] != "")
                {
                    postion = int.Parse(frm["Position"]);
                }
                // TODO: Add insert logic here
                Models.Menu ad = new Models.Menu()
                {
                    Subject = frm["Subject"],
                    TextTooltip = frm["TextTooltip"],
                    Links = frm["Links"],
                    Position = postion
                };

                kt = MenuBusiness.AddMenu(ad);
            }
            catch
            {
                kt = 0;
            }

            if (kt > 0)
            {
                return RedirectToAction("ListMenu", "Menus", new { add = "success" });
            }
            else
            {
                return RedirectToAction("ListMenu", "Menus", new { add = "error" });
            }
        }

        //
        // GET: /Admin/Menu/Edit/5

        public ActionResult Edit(int id)
        {
            if (Session["mvc_user"] != null)
            {
                Models.Admin ad = Session["mvc_user"] as Models.Admin;
                if (!ad.IsSuperAdmin)
                {
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }

            List<Menu> ls = MenuBusiness.GetMenuById(id);

            return View(ls[0]);
        }

        //
        // POST: /Admin/Menu/Edit/5

        [HttpPost]
        public ActionResult EditProcess(FormCollection frm)
        {
            int kt = 0;
            try
            {

                int? postion = null;
                if (frm["Position"] != null && frm["Position"] != "")
                {
                    postion = int.Parse(frm["Position"]);
                }
                // TODO: Add insert logic here
                Models.Menu ad = new Models.Menu()
                {
                    Id = int.Parse(frm["Id"]),
                    Subject = frm["Subject"],
                    TextTooltip = frm["TextTooltip"],
                    Links = frm["Links"],
                    Position = postion
                };

                kt = MenuBusiness.EditMenu(ad);
            }
            catch
            {
                kt = 0;
            }

            if (kt > 0)
            {
                return RedirectToAction("ListMenu", "Menus", new { update = "success" });
            }
            else
            {
                return RedirectToAction("ListMenu", "Menus", new { update = "error" });
            }
        }

        //
        // GET: /Admin/Menu/Delete/5

        public ActionResult Delete(int id)
        {
            if (Session["mvc_user"] != null)
            {
                Models.Admin ad = Session["mvc_user"] as Models.Admin;
                if (!ad.IsSuperAdmin)
                {
                    return RedirectToAction("Index", "HomeAdmin");
                }
            }

            int kt = 0;
            try
            {
                kt = MenuBusiness.DeleteMenu(id);
            }
            catch
            {
                kt = 0;
            }

            if (kt > 0)
            {
                return RedirectToAction("ListMenu", "Menus", new { delete = "success" });
            }
            else
            {
                return RedirectToAction("ListMenu", "Menus", new { delete = "error" });
            }

        }


    }
}

SourceCode/NGOWebsite/NGOWebsite/Controllers/InformationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BusinessLogicLayer;

namespace NGOWebsite.Controllers
{
    public class InformationsController : Controller
    {
        //
        // GET: /Information/

        

        public ActionResult ReadAboutUs()
        {
            return View();
        }
        public ActionResult WhatWeDo()
        {
            return View();
        }
        public ActionResult OurMission()
        {
            return View();
        }
        public ActionResult OurTeam()
        {
            return View();
        }
        public ActionResult OurAchievements()
        {
            return View();
        }
        public ActionResult OurSupporters()
        {
            return View();
        }
    }
}

SourceCode/NGOWebsite/NGOWebsite/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogicLayer;
using Models;

namespace NGOWebsite.Controllers
{
    public class MenuController : Controller
    {
        //
        // GET: /Menu/
        [ChildActionOnly]
        public ActionResult Index()
        {
            List<Models.Menu> ls = MenuBusiness.GetAllMenuPostionNotNull();
            //List<Models.Menu> ls = MenuBusiness.GetAllMenu();
            List<Models.Informations> ls1 = InformationsBusiness.GetAllInformations().Where(d=> d.ParentId!=null).ToList();

            ViewData["submenu"] = ls1;

            return PartialView(ls);


        }


    }
}

SourceCode/NGOWebsite/NGOWebsite/Areas/Admin/Views/Menus/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@model Models.Menu

<div class="row" style="margin-top:30px">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-weight:bold">
                <i class="fa fa-th-list  fa-fw"></i> Add New Menu Item
            </div>
            <div class="panel-body">
                <div class="row">

                    @using (Html.BeginForm("CreateProcess", "Menus", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <div class="col-lg-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject)
                                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                                @Html.ValidationMessageFor(model => model.Subject)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.TextTooltip)
                                @Html.TextBoxFor(model => model.TextTooltip, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "100" })
                                @Html.ValidationMessageFor(model => model.TextTooltip)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Links)
                                @Html.TextBoxFor(model => model.Links, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "100" })
                                @Html.ValidationMessageFor(model => model.Links)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Position)
                                @Html.TextBoxFor(model => model.Position, new { @class = "form-control", @placeholder = "Enter number",@maxlength = "2" })
                                @Html.ValidationMessageFor(model => model.Position)
                            </div>

                        </div>
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-primary" style="margin-top:25px;width:120px"><i class="fa fa-plus-circle  fa-fw"></i> Add New </button>
                            <button type="reset" class="btn btn-primary" style="margin-top: 25px;margin-left:30px; width: 120px"><i class="fa  fa-refresh  fa-fw"></i> Reset </button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Areas/Admin/Views/Menus/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@model Models.Menu

<div class="row" style="margin-top:30px">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-weight:bold">
                <i class="fa fa-th-list  fa-fw"></i> Menu Item Details
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <tr>
                                <th style="width:20%">
                                    @Html.LabelFor(model => model.Subject)
                                </th>
                                <td>
                                    @Html.DisplayTextFor(model => model.Subject)
                                </td>
                            </tr>
                            <tr>
                                <th style="width:20%">
                                    @Html.LabelFor(model => model.TextTooltip)
                                </th>
                                <td>
                                    @Html.DisplayTextFor(model => model.TextTooltip)
                                </td>
                            </tr>
                            <tr>
                                <th style="width:20%">
                                    @Html.LabelFor(model => model.Position)
                                </th>
                                <td>
                                    @Html.DisplayTextFor(model => model.Position)
                                </td>
                            </tr>
                            <tr>
                                <th style="width:20%">
                                    @Html.LabelFor(model => model.Links)
                                </th>
                                <td>
                                    @Html.DisplayTextFor(model => model.Links)
                                </td>
                            </tr>
                            
                        </table>

                    </div>
                    <div class="col-lg-4">
                        <a class="btn btn-primary" style="margin-top: 15px; width: 120px" href="@Url.Action("Edit", "Menus", new { id = Model.Id })"><i class="fa fa-edit  fa-fw"></i> Update </a><br/>
                        <a class="btn btn-danger" style="margin-top:15px;width:120px" href="@Url.Action("Delete", "Menus", new { @id = Model.Id })" onclick="return confirm('Are you sure?');"><i class="fa fa-times-circle  fa-fw"></i> Delete </a><br/>
                        <a class="btn btn-success" style="margin-top:15px;width:120px" href="@Url.Action("ListMenu", "Menus")"><i class="fa fa-mail-reply  fa-fw"></i> Back to list </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


SourceCode/NGOWebsite/NGOWebsite/Areas/Admin/Views/Menus/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@model Models.Menu

<div class="row" style="margin-top:30px">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-weight:bold">
                <i class="fa fa-th-list  fa-fw"></i> Add New Menu Item
            </div>
            <div class="panel-body">
                <div class="row">

                    @using (Html.BeginForm("EditProcess", "Menus", FormMethod.Post))
                    {
                        @Html.HiddenFor(model => model.Id)
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                        <div class="col-lg-8">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Subject)
                                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                                @Html.ValidationMessageFor(model => model.Subject)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.TextTooltip)
                                @Html.TextBoxFor(model => model.TextTooltip, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "100" })
                                @Html.ValidationMessageFor(model => model.TextTooltip)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Links)
                                @Html.TextBoxFor(model => model.Links, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "100" })
                                @Html.ValidationMessageFor(model => model.Links)
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Position)
                                @Html.TextBoxFor(model => model.Position, new { @class = "form-control", @placeholder = "Enter number", @maxlength = "2" })
                                @Html.ValidationMessageFor(model => model.Position)
                            </div>

                        </div>
                        <div class="col-lg-4">
                            <button type="submit" class="btn btn-primary" style="margin-top:25px;width:120px"><i class="fa fa-edit  fa-fw"></i> Update </button><br/>
                            <a class="btn btn-primary" style="margin-top: 15px;margin-left:30px; width: 120px" href="@Url.Action("ListMenu","Menus")"><i class="fa  fa-mail-reply fa-fw"></i> Cancel </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Areas/Admin/Views/Menus/ListMenu.cshtml
@{
    ViewBag.Title = "ListMenu";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using Models
@model IEnumerable<Models.Menu>

<script>
    $(document).ready(function () {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>

<div class="row">

    <div class="col-lg-12">
        @{
            if (Request.QueryString.Count > 0)
            {
                string key = Request.QueryString.GetKey(0);
                string value = Request.QueryString.Get(0);
                switch (value)
                {
                    case "success":
                        <div class="alert alert-success" style="text-align:center;margin-top:30px;margin-bottom:-10px">
                            <i class="fa fa-check-circle  fa-fw"></i> Successfull !
                        </div>

                        break;
                    case "error":
                    <div class="alert alert-danger" style="text-align: center; margin-top: 30px; margin-bottom: -10px">
                        <i class="fa fa-times-circle  fa-fw"></i> Something went wrong !
                    </div>
                        break;
                }
            }
        }
    </div>

</div>
<!-- /.row -->
<div class="row" style="margin-top:30px">
    <div class="col-lg-12">
        <a class="btn btn-primary" href="@Url.Action("Create", "Menus")"><i class="fa fa-plus-circle  fa-fw"></i>Add New</a>
    </div>
</div>
<div class="row" style="margin-top:10px">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-weight:bold">
                <i class="fa fa-th-list  fa-fw"></i> List Menu
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model.Id)</th>
                                <th>@Html.DisplayNameFor(model => model.Subject)</th>
                                <th>@Html.DisplayNameFor(model => model.Links)</th>
                                <th>@Html.DisplayNameFor(model => model.TextTooltip)</th>
                                <th>@Html.DisplayNameFor(model => model.Position)</th>
                                <th>Submenu</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Subject)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Links)</td>
                                    <td>@Html.DisplayFor(modelItem => item.TextTooltip)</td>
                                    <td>@Html.DisplayFor(modelItem => item.Position)</td>
                                    <td>
                                        <a href="@Url.Action("Submenu", "Informations", new { parentId=item.Id})" title="View Submenu"><i class="fa fa-search-plus  fa-fw"></i>View Submenu</a>
                                    </td>
                                    <td style="text-align:center">
                                        <a href="@Url.Action("Details", "Menus", new { id=item.Id})" title="View Detail"><i class="fa fa-search-plus  fa-fw"></i></a>
                                        <a href="@Url.Action("Edit", "Menus", new { id = item.Id })" title="Update"><i class="fa fa-edit  fa-fw"></i></a>
                                        <a href="@Url.Action("Delete", "Menus", new { id = item.Id })" onclick="return confirm('Are you sure?');" title="Delete"><i class="fa fa-times  fa-fw"></i></a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}









