SourceCode/NGOWebsite/NGOWebsite/Controllers/InformationssController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogicLayer;
using Models;

namespace NGOWebsite.Controllers
{
    public class InformationssController : Controller
    {
        //
        // GET: /Informationss/

        public ActionResult OurAchievements()
        {
            List<Models.Informations> about = InformationsBusiness.GetInformationsById(5);
            return View(about[0]);
        }
        public ActionResult OurMission()
        {
            List<Models.Informations> about = InformationsBusiness.GetInformationsById(2);
            return View(about[0]);
        }
        public ActionResult OurSupporters()
        {
            List<Models.Informations> about = InformationsBusiness.GetInformationsById(6);
            return View(about[0]);
        }
        public ActionResult OurTeam()
        {
            //List<Models.Informations> about = InformationsBusiness.GetInformationsById(3);
            List<Models.Member> ls = MemberBusiness.GetAllMember().Where(d => d.IsMemberOfTeam == 1).ToList();
            return View(ls);
        }
        public ActionResult ReadAboutUs()
        {
            List<Models.Informations> about = InformationsBusiness.GetInformationsById(7);
            return View(about[0]);
        }
        public ActionResult WhatWeDo()
        {
            List<Models.Informations> about = InformationsBusiness.GetInformationsById(1);
            return View(about[0]);
        }

        public ActionResult NewsDetail(int id)
        {
            List<Informations> ls1=InformationsBusiness.GetInformationsById(id);
            Informations info = ls1[0];
            ViewData["info"] = info;
            Random rnd=new Random();
            List<Informations> ls = InformationsBusiness.GetAllInformations().Where(d => d.ParentId == null).OrderBy(q => Guid.NewGuid()).Take(10).ToList();
            ViewData["lsRandom"] = ls;

            return View();
        }
    }

   
}

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/NewsDetail.cshtml
@{
    ViewBag.Title = "NewsDetail";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@model Models.Informations
@using Models

@{
    Informations info = ViewData["info"] as Informations;
}

<style type="text/css">
    .newContent {
        text-indent: 30px;
        text-transform: capitalize;
    }

            .newContent p span {
                font-size: 20px !important;
                
            }
</style>



<div class="recent_news">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12 heading dark animate_top"><span>@Html.DisplayName(info.Subject)</span></div>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-10 text-justify animate_bottom" style="padding-bottom:30px">
            <p>@Html.Raw(info.Contents)</p>
        </div>
        <div class="col-md-1"></div>
        <p style="border-bottom:1px solid gray"> </p>



        @if (ViewData["lsRandom"] != null)
        {
            <div class="row ">
                <div class="col-md-12 dark animate_top text-center heading">Others News</div>
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    @{
            List<Informations> ls = ViewData["lsRandom"] as List<Informations>;
            foreach (Informations item in ls)
            {<div class="col-md-6">
                <a style="font-size:20px;font-weight:bold" href="@Url.Action("NewsDetail", "Informationss", new { id=item.Id})"> @item.Subject </a><br />
                <div class="newContent">
                    @Html.Raw(DataAccessLayer.DataConnect.SubStringText(item.Contents))
                </div>
                <p class="readmore"><a href="@Url.Action("NewsDetail", "Informationss", new { @id = item.Id })">...read more</a></p>
                <hr style="height:1px;color:gray" />
            </div>
            }}
                </div>
                <div class="col-md-1"></div>

            </div>
        }
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/OurAchievements.cshtml
@model Models.Informations
@{
    ViewBag.Title = "OurAchievements";
}
<style type="text/css">
    .col-md-10 p {
        color: green;
        text-align: justify;
        text-indent: 30px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12 heading dark text-center animate_top">Our Achievements</div>
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center animate_bottom">

            <p>@Html.Raw(Model.Contents)</p>
        </div>
        <div class="col-md-1"></div>

    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/OurMission.cshtml
@model Models.Informations
@{
    ViewBag.Title = "OurMission";
}

<style type="text/css">
    .col-md-10 p {
        text-align: justify;
        text-indent: 30px;
    }
</style>
<div class="how_can_you_help_bg parallax" id="help">
    <div class="how_can_you_help">
        <div class="container">
            <div class="col-md-12 heading dark text-center animate_top">Our  Mission</div>
            <div class="col-md-1"></div>
            <div class="col-md-10 text-center animate_bottom">
                <p>@Html.Raw(Model.Contents)</p>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/OurSupporters.cshtml
@model Models.Informations
@{
    ViewBag.Title = "OurSupporters";
}

<style type="text/css">
    .col-md-10 p {
        text-align: justify;
        text-indent: 30px;
    }
</style>
<div class="how_can_you_help_bg parallax" id="help">
    <div class="how_can_you_help">
        <div class="container">
            
            <div class="row">
                <div class="col-md-12 heading dark text-center animate_top">Our  supporters</div>
                <div class="col-md-1"></div>
                <div class="col-md-10 text-center animate_bottom">
                    <p>@Html.Raw(Model.Contents)</p>
                </div>
                <div class="col-md-1"></div>
            </div>
        </div>
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/OurTeam.cshtml
@{
    ViewBag.Title = "OurTeam";
}

@model IEnumerable<Models.Member>

<!-- About us -->
<div class="team">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center heading dark animate_top">
                All about <span>our team</span> Website
            </div>
        </div>

        @{var flag = 0;}
        @foreach (Models.Member item in Model)
        {
            flag++;
            if (flag % 2 != 0)
            {
                <div class="row t1">
                    <div class="col-md-3 animate_left">
                        <img src="~/@item.Image" alt="img" />
                    </div>
                    <div class="col-md-9 animate_right">
                        <h1>@item.FullName</h1>
                        <h3>Gender</h3>
                        <p>@item.Gender</p>
                        <h3>E-mail</h3>
                        <p>@item.Email</p>
                        <h3>Address</h3>
                        <p>@item.Address</p>
                        <h3>Phone</h3>
                        <p>@item.Phone</p>
                        <ul>
                            <li><a href=""><i class="fa fa-twitter"></i></a></li>
                            <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            }
            else
            {
            <div class="row t1">
                <div class="col-md-9 animate_right">
                    <h1>@item.FullName</h1>
                    <h3>Gender</h3>
                    <p>@item.Gender</p>
                    <h3>E-mail</h3>
                    <p>@item.Email</p>
                    <h3>Address</h3>
                    <p>@item.Address</p>
                    <h3>Phone</h3>
                    <p>@item.Phone</p>
                    <ul>
                        <li><a href=""><i class="fa fa-twitter"></i></a></li>
                        <li><a href=""><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>


                <div class="col-md-3 animate_left">
                    <img src="~/@item.Image" alt="img">

                </div>
            </div>
            }
        }
    </div>


</div><!-- End call action text -->

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/ReadAboutUs.cshtml
@model Models.Informations
@{
    ViewBag.Title = "ReadAboutUs";
}
@*<div class="container">
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10 welcome_txt text-center animate_bottom">
                <p>Lorem Ipsum has been the industry's standard dummy text ever since the <span>1500s</span>, when an unknown <span>printer</span> took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining unchanged. It was <span>popularised</span> in the 1960s.
                </p>
            </div>
            <div class="col-md-1"></div>
        </div>
    </div>*@
<!-- About us -->

<style type="text/css">
    .col-md-10 p {
        text-align: justify;
        text-indent: 30px;
    }
</style>
<div class="about_us">
    <div class="container">
        <div class="row text-center">

            <h1 class="heading">All about <span>NGO</span> Website</h1>
            <div class="col-md-1"></div>
            <div class="col-md-10 animate_left">
                <p class="">@Html.Raw(Model.Contents)</p>
            </div>

            <div class="col-md-1"></div>


        </div><!-- End call action text -->
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Informationss/WhatWeDo.cshtml
@model Models.Informations
@{
    ViewBag.Title = "WhatWeDo";
}
<style type="text/css">
    .col-md-10 p {
        color: green;
        text-align: justify;
        text-indent: 30px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-12 heading dark text-center animate_top">What  <span>we do</span></div>
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center animate_bottom">
            <p>@Html.Raw(Model.Contents)</p>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>