SourceCode/NGOWebsite/NGOWebsite/Controllers/ProgramsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BusinessLogicLayer;

namespace NGOWebsite.Controllers
{
    public class ProgramsController : Controller
    {
        //
        // GET: /Programs/

        public ActionResult Programs()
        {

            return View();
        }

        public ActionResult ListProgram(string type)
        {
            ViewData["type"] = type;
            List<Models.ImageGallery> lsTopic = ImageGalleryBusiness.GetImageTopicPrograms();
            ViewData["lsTopicPrograms"] = lsTopic;

            List<Models.Programs> ls = ProgramsBusiness.GetAllPrograms();
            if (type == "upcoming")
            {
                ls = ls.Where(d => d.Status == 0).ToList();
            }
            else if (type == "recent")
            {
                ls = ls.Where(d => d.Status == 1).ToList();
            }
            else
            {
                ls = ls.Where(d => d.Status == 2).ToList();
            }
            return View(ls);
        }

        public ActionResult PartialViewProgram(string type)
        {
            List<Models.ImageGallery> lsTopic = ImageGalleryBusiness.GetImageTopicPrograms();
            ViewData["lsTopicPrograms"] = lsTopic;
            ViewData["type"] = type;

            List<Models.Programs> ls = ProgramsBusiness.GetAllPrograms();
            if (type == "upcoming")
            {
                ls = ls.Where(d => d.Status == 0).Take(3).ToList();
            }
            else if (type == "recent")
            {
                ls = ls.Where(d => d.Status == 1).Take(3).ToList();
            }
            else
            {
                ls = ls.Where(d => d.Status == 2).Take(3).ToList();
            }

            return PartialView(ls);
        }

        public ActionResult ProgramDetail(int id)
        {
            List<Models.ImageGallery> lsTopic = ImageGalleryBusiness.GetImageTopicPrograms();
            foreach (var item in lsTopic)
            {
                if (item.ProgramId == id)
                {

                    ViewData["ls1"] = item;
                }
            }
            if (Session["user_login"] != null)
            {

                List<Models.Programs> ls = ProgramsBusiness.GetProgramsById(id);
                ViewData["program"] = ls[0];
                Models.Member ad = Session["user_login"] as Models.Member;
                Models.Message msg = new Models.Message();
                msg.SenderName = ad.FullName;
                msg.SenderEmail = ad.Email;
                return View(msg);

            }
            else
            {
                List<Models.Programs> ls = ProgramsBusiness.GetProgramsById(id);
                ViewData["program"] = ls[0];
                return View();
            }
            

            
            
            
        }

    }
}

SourceCode/NGOWebsite/NGOWebsite/Views/Programs/ListProgram.cshtml
@{
    ViewBag.Title = "ListProgram";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

@using DataAccessLayer;

@model IEnumerable<Models.Programs>
@{
    string type="";
    if(ViewData["type"]!=null){
        type=ViewData["type"].ToString();
    }
}
<div class="recent_news" id="recent_news">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12 heading dark animate_top">
                @if (type == "upcoming")
                {
                    @Html.DisplayName("Upcoming")
                }else if(type=="recent"){
                    @Html.DisplayName("Recent")
                }
                else
                {
                    @Html.DisplayName("Complete")
                }
                <span>Programs</span>
            </div>
        </div>
        <div class="row act">
            @{List<Models.ImageGallery> listImg;
            listImg = ViewData["lsTopicPrograms"] as List<Models.ImageGallery>;
            }
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    @foreach (var i in listImg)
                    {
                        if (i.ProgramName == @item.Name)
                        {
                            <img src="~/@i.ImagePath" alt="img" class="animate_top" width="300px" height="200px" />
                        }
                    }

                    <div class="animate_bottom s1">
                        <h4><a href="@Url.Action("ProgramDetail", "Programs", new { @id = item.Id })">@item.Name</a></h4>
                        <p class="date">Issie 18 - 24 October 2015</p>
                        <p class="meta">
                            <i class="fa fa-calendar"></i>August 5, 2015<br>
                            <i class="fa fa-clock-o"></i>9:00am - 1:00pm<br>
                            <i class="fa fa-map-marker"></i>TheWebLab
                        </p>
                        <p class="readmore"><a href="@Url.Action("ProgramDetail", "Programs", new { @id = item.Id })">...read more</a></p>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

SourceCode/NGOWebsite/NGOWebsite/Views/Programs/PartialViewProgram.cshtml
@model IEnumerable<Models.Programs>

@{
    string type = "";
    if (ViewData["type"] != null)
    {
        type = ViewData["type"].ToString();
    }
}

<div class="row act">
    <div class="row">
        @{List<Models.ImageGallery> listImg;
        listImg = ViewData["lsTopicPrograms"] as List<Models.ImageGallery>;
        }
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                @foreach (var i in listImg)
                {
                    if (i.ProgramName == @item.Name)
                    {
                        <img src="~/@i.ImagePath" alt="img" class="animate_top" width="300px" height="200px" />
                    }
                }

                <div class="animate_bottom s1">
                    <h4><a href="@Url.Action("ProgramDetail", "Programs", new { @id = item.Id })">@item.Name</a></h4>
                    <p class="date">Issie 18 - 24 October 2015</p>
                    <p class="meta">
                        <i class="fa fa-calendar"></i>August 5, 2015<br>
                        <i class="fa fa-clock-o"></i>9:00am - 1:00pm<br>
                        <i class="fa fa-map-marker"></i>TheWebLab
                    </p>

                    <p class="readmore"><a href="@Url.Action("ProgramDetail", "Programs", new { @id = item.Id })">...read more</a></p>
                </div>
            </div>
        }
    </div>
    <div class="row">
        <a class="top_btn2" style="float:right;margin-right:15px" href="@Url.Action("ListProgram", "Programs", new {type=type })">Read more...</a>
    </div>
</div>

SourceCode/NGOWebsite/NGOWebsite/Views/Programs/ProgramDetail.cshtml
@{
    ViewBag.Title = "Program";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@*<style>
        #custom-content img {
            max-width: 100%;
            margin-bottom: 10px;
        }
    </style>*@
<style type="text/css">
    p {
        color: black;
    }

</style>
@model Models.Message

@{Models.ImageGallery ls1 = new Models.ImageGallery();
if (ViewData["ls1"] != null)
{
    ls1 = ViewData["ls1"] as Models.ImageGallery;
}
}



@{
    Models.Programs program = new Models.Programs();
    if (ViewData["program"] != null)
    {
        program = ViewData["program"] as Models.Programs;
    }
}

<div class="contact-bg parallax" id="contact">
    <div class="contact">
        <div class="container">
            @if (Request.QueryString["add"] != null)
            {
                if (Request.QueryString["add"].Equals("error"))
                {
                    <div class="alert alert-danger" style="text-align: center; margin-top: 30px; margin-bottom: -50px">
                        <img src='~/Content/View_components/images/error.png' alt="img">Send Message Fail !

                    </div>

                }
                else
                {
                    <div class="alert alert-success" style="text-align: center; margin-top: 30px; margin-bottom: -50px">
                        <img src='~/Content/View_components/images/success.png' alt="img">Send Message Successfully !

                    </div>
                }
            }

            <div class="row">
                <div class="row">
                    <div class="col-md-12 text-center heading animate_top"> @program.Name </div>
                </div>
                <div class="col-md-5 text-center">

                    <img src="~/@ls1.ImagePath" alt="img" width="300px" height="300px">
                </div>
                <div class="col-md-7">
                    <p class="date">18 - 24 October 2015</p>
                    <h3>@Html.Raw(program.Contents)</h3>
                </div>


            </div>

            <div class="row">

                <div class="col-md-5 text-center">
                    @if (program.Status == 0 || program.Status == 1)
                    {
                        <a class="top_btn2" href="@Url.Action("Donate", "Donate", new {proId=program.Id })">Donate Now</a>
                    }
                    <div class="col-md-12 text-center heading animate_top">Send message <span class="brd">for this program</span></div>
                </div>
                <div class="col-md-6 contact_form animate_left">

                    @using (Html.BeginForm("AddMsgProcess", "Message", FormMethod.Post))
                    {

                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)

                        <div class="form-group">
                            @Html.LabelFor(model => model.SenderName)
                            @Html.TextBoxFor(model => model.SenderName, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                            @Html.ValidationMessageFor(model => model.SenderName)

                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.SenderEmail)
                            @Html.TextBoxFor(model => model.SenderEmail, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                            @Html.ValidationMessageFor(model => model.SenderEmail)
                        </div>

                        <div class="form-group">
                            @Html.Hidden("programId", program.Id)
                            @Html.Hidden("sender", "recentPro")
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.Messages)
                            @Html.TextAreaFor(model => model.Messages, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "300" })
                            @Html.ValidationMessageFor(model => model.Messages)

                        </div>

                        <button class="bttn" id='send' type="submit">Send</button>
                        <button class="bttn" id='cancel' type="reset">Reset</button>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

SourceCode/NGOWebsite/NGOWebsite/Views/Programs/Programs.cshtml
@{
    ViewBag.Title = "Program";
    Layout = "~/Views/Shared/_UserLayout.cshtml";

}

@using DataAccessLayer;

@model IEnumerable<Models.Programs>

<div class="recent_news" id="recent_news">
    <div class="container">
       

        <div class="col-md-12 heading dark animate_left">Recent <span>Programs</span></div>
        @{Html.RenderAction("PartialViewProgram", "Programs", new { type = "recent" });}

        <div class="col-md-12 heading dark animate_left">Upcoming <span>Programs</span></div>
        @{Html.RenderAction("PartialViewProgram", "Programs", new { type = "upcoming" });}

        <div class="col-md-12 heading dark animate_left">Complete <span>Programs</span></div>
        @{Html.RenderAction("PartialViewProgram", "Programs", new { type = "complete" });}

        
    </div>
</div>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

SourceCode/NGOWebsite/NGOWebsite/Views/Programs/RecentProgram.cshtml
@{
    ViewBag.Title = "Program";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@*<style>
    #custom-content img {
        max-width: 100%;
        margin-bottom: 10px;
    }
</style>*@
@model Models.Message
@{Models.ImageGallery ls1;
  ls1 = ViewData["ls1"] as Models.ImageGallery;
}



@{Models.Programs program;
  program = ViewData["program"] as Models.Programs;
}

<div class="contact-bg parallax" id="contact">
    <div class="contact">
        <div class="container">
            @if (Request.QueryString["add"] != null)
            {
                if (Request.QueryString["add"].Equals("error"))
                {
                <div class="alert alert-danger" style="text-align: center; margin-top: 30px; margin-bottom: -50px">
                    <img src='~/Content/View_components/images/error.png' alt="img">Send Message Fail !
                    
                </div>
                
                }
                else
                {
                <div class="alert alert-success" style="text-align: center; margin-top: 30px; margin-bottom: -50px">
                    <img src='~/Content/View_components/images/success.png' alt="img">Send Message Successfully !

                </div>
                }
            }

            <div class="row">
                @if (program != null)
                {<div class="row">
                    <div class="col-md-12 text-center heading animate_top">@program.Name</div>
                </div>
                    <div class="col-md-5 text-center">

                        <img src="~/@ls1.ImagePath" alt="img" width="300px" height="300px">
                    </div>
                    <div class="col-md-7">
                        <p class="date">18 - 24 October 2015</p>
                        <h3>@program.Contents</h3>
                    </div>
                    
                }
            </div>

            <div class="row">

                <div class="col-md-5 text-center"><a class="top_btn2" href="@Url.Action("Donate", "Donate")">Donate Now</a>
                    <div class="col-md-12 text-center heading animate_top">Send message <span class="brd">for this program</span></div>
                </div>
                <div class="col-md-6 contact_form animate_left">


                    @using (Html.BeginForm("AddMsgProcess", "Message", FormMethod.Post))
                    {
                        
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true)
                          
                        <div class="form-group">
                            @Html.LabelFor(model => model.SenderName)
                            @Html.TextBoxFor(model => model.SenderName, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                            @Html.ValidationMessageFor(model => model.SenderName)

                        </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.SenderEmail)
                            @Html.TextBoxFor(model => model.SenderEmail, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "50" })
                            @Html.ValidationMessageFor(model => model.SenderEmail)
                        </div>
                       
                        <div class="form-group">
                            @Html.Hidden("programId", program.Id)
                            @Html.Hidden("sender", "recentPro")
                        </div>
                            

                        <div class="form-group">
                            @Html.LabelFor(model => model.Messages)
                            @Html.TextAreaFor(model => model.Messages, new { @class = "form-control", @placeholder = "Enter text", @maxlength = "300" })
                            @Html.ValidationMessageFor(model => model.Messages)

                        </div>
                        
                        <button class="bttn" id='send' type="submit">Send</button>
                        <button class="bttn" id='cancel' type="reset">Reset</button>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts 
{
    @Scripts.Render("~/bundles/jqueryval")
}